### ISSUE TITLE
It appears selectedItem.name should selectedItem[selectedItem.name]

### ISSUE THREAD

**Issue by dylansproule** [manish-nepal/vue3-select-option-searchable#2]
It appears selectedItem.name should selectedItem[selectOptionProps.displayName]

Currently only the list item is updated.

Best,
Dylan

**Comment by manish-nepal** [comment]
Hello Dylan, selectedItem.name works fine, i've shown this selectedItem.name example just to show how the package is used. I double checked it now too. Can you please try again and let me know if the problem still persist's.

**Comment by dylansproule** [comment]
Thanks for getting back to me, sorry I was referring to the Vue component:

https://github.com/manish-nepal/vue3-select-option-searchable/blob/main/src/components/SelectOption.vue

Line 8:
`v-model="selectedItem.name" @input="handleSearch" @click="handleInput" @keydown.enter="handleEnter"`

and Line 18:
`<div class="clear-icon" v-if="selectedItem.name" @click="clearSearch">`

**Comment by manish-nepal** [comment]
> Thanks for getting back to me, sorry I was referring to the Vue component:
> 
> https://github.com/manish-nepal/vue3-select-option-searchable/blob/main/src/components/SelectOption.vue
> 
> Line 8: `v-model="selectedItem.name" @input="handleSearch" @click="handleInput" @keydown.enter="handleEnter"`
> 
> and Line 18: `<div class="clear-icon" v-if="selectedItem.name" @click="clearSearch">`

Thanks Dylan for pointing out this, I've fixed the issue, Please do update the package

**Comment by dylansproule** [comment]
Confirmed the updates work as intended, thanks again
